### ISSUE TITLE
progress update

### ISSUE THREAD

**Issue by ericzon** [dominicrico/angular-reading-indicator#2]
It'd be great to update the remaining time based on the unread lines (out of the screen).

**Comment by dominicrico** [comment]
Great idea! I will implement this asap!

**Comment by dominicrico** [comment]
I implemented that now, but just a bit different. I based the remaining reading time on the progress, hope that is fine for you too.

**Comment by ericzon** [comment]
well, it's not so accurate but it's ok for me, thx  :)
